name: CI
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: elementary/actions/vala-lint@master
  flatpak:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:7.2
      options: --priveleged
    steps:
      - uses: actions/checkout@v3
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: pachy.flatpak
          manifest-path: com.github.leggettc18.pachy.yml
          run-tests: true
          repository-name: appcenter
          repository-url: https://flatpak.elementary.io/repo.flatpakrepo
          cache-key: "flatpak-builder-${{ github.sha }}"
